### ISSUE TITLE
I can't find the hair_prob.npy file and eye_prob.npy file in this project

### ISSUE THREAD

**Issue by mymelove02** [Mckinsey666/Anime-Generation#3]
Thanks for your sharing！However,I can't find the hair_prob.npy file and eye_prob.npy file in this project.And the training data downloaded from https://drive.google.com/file/d/1jdJXkQIWVGOeb0XJIXE3YuZQeiEPd8rM/view?usp=sharing doesn't contain a tags.pickle file.Could you please tell me how to get these three files so that I can run train.py successfully?

**Comment by bchao1** [comment]
Hi there. I've been restructuring code and cleaning the datasets, so it took me a while to get back to you. The new dataset has 100K images, and I've added the link in the new readme. Go check it out!
